### ISSUE TITLE
tibblify got archived on CRAN?

### ISSUE THREAD

**Issue by pat-s** [mgirlich/tibblify#158]
```
Package ‘tibblify’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/tibblify).

Archived on 2022-08-08 as issues were not corrected in time.
```

Are there plans to bring it back?

**Comment by mgirlich** [comment]
Argh, I overlooked the email where they asked me for fixing it. Thanks for informing me! But I thought there would have been more than one email... Also it is a minor thing (non-ascii character in some of the data).
I'll work on it next week and hope to add some features as well.

**Comment by krlmlr** [comment]
Are you planning substantial changes that make it worthwhile keeping the package off CRAN for longer? Do you need help fixing things?

**Comment by mgirlich** [comment]
Sorry, I started working on it and discovered a big memory leak which I wanted to fix first. Then I got caught up in other work first. Now that it is fixed I plan to have it available on CRAN again soon. Thanks for offering your help!

**Comment by mgirlich** [comment]
Finally back on CRAN 🥳
