### ISSUE TITLE
Should the default for `tib_vector()` be `NULL` or ``vec_init(ptype, 0)`?

### ISSUE THREAD

**Issue by mgirlich** [mgirlich/tibblify#35]
Currently it is `vec_init(ptype, 0)` but it might be better to use `NULL` instead.

**Comment by krlmlr** [comment]
A `NULL` default makes slightly more sense to me, it's then also distinguishable from an empty vector.

**Comment by mgirlich** [comment]
It also makes more sense to me now. Sometimes it can be annoying to have `NULL` instead of e.g. `character()` when iterating over a list. But as vctrs recognizes `NULL` as missing value in lists and with `%||%` it is much easier to work with then with `character()`.
