### ISSUE TITLE
Add path to error message in `vec_cast()`

### ISSUE THREAD

**Issue by mgirlich** [mgirlich/tibblify#36]
The path should be shown when casting is not possible:

``` r
spec <- spec_df(a = tib_int("a"))
x <- list(list(a = 1), list(a = "a"))

tibblify(x, spec)
#> Error:
#> ! Can't convert <character> to <integer>.

# This should be something like
#> Error:
#> ! Can't convert <character> to <integer> at path $a[[2]].
```

<sup>Created on 2022-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The error `vec_cast()` throws needs to be caught and the path object needs to be added. Not sure how this can be done at C level.

**Comment by krlmlr** [comment]
Done by #52?

**Comment by mgirlich** [comment]
No. I added an example to the description.

**Comment by krlmlr** [comment]
This sounds hard.

What if `tibblify_impl()` ran in an overarching `tryCatch()`, and we kept track of the current path so that we can use it for an error message? Would this also simplify the internal error handling?

**Comment by mgirlich** [comment]
This might work. I'll have a look at it.

**Comment by krlmlr** [comment]
I believe this requires the current `Path` to be either a global variable (which can be queried even after `tibblify_impl()` throws an error), or that we establish a context object (an external pointer?) before running `tibblify_impl()` that contains the `Path` object. Either way it would be a great addition.

**Comment by mgirlich** [comment]
Do you want to have a look at it?

By the way I would like to submit to CRAN soon in order to get tibblify back to CRAN before their summer break. Are there things you would really like to have included in that release?

**Comment by krlmlr** [comment]
I might, the next time I need to find the reason for a parsing failure 🙃

**Comment by krlmlr** [comment]
The 0.2 milestone looks good, I don't really have excess capacity before September though.
