### ISSUE TITLE
Support intermediate type and vectorised transform?

### ISSUE THREAD

**Issue by mgirlich** [mgirlich/tibblify#48]
For example for dates stored as character. Interface could be something like

```r
tib_scalar(
  "key",
  ptype_out = new_date(),
  ptype_in = character(),
  default = new_date(NA_real_),
  elt_transform = NULL,
  all_transform = lubridate::ymd
)
```

This would make #47 trivial

**Comment by krlmlr** [comment]
Vectorized transform sounds interesting.

Instead of intermediate types, should we offer better support for transforming tibbles into tibbles, so that we can have a data ingestion stage (structured but only bare types) and a cleanup stage (with tranformations, default values, ...)?
