### ISSUE TITLE
Combine two or more specs?

### ISSUE THREAD

**Issue by krlmlr** [mgirlich/tibblify#65]
Do we need a `spec_common()` that takes an arbitrary number of spec objects and computes a common spec?

Invariant proposal: `spec_guess(x)` should be the same as `spec_common(!!!map(x, spec_guess))` .

Would that help get a better understanding of #63?

``` r
library(tidyverse)
tibblify::guess_spec(list(books = repurrrsive::got_chars[[1]]$books))
#> spec_object(
#>   books = tib_chr_vec("books")
#> )
tibblify::guess_spec(list(books = repurrrsive::got_chars[[10]]$books))
#> spec_object(
#>   books = tib_chr("books")
#> )
tibblify::guess_spec(list(books = repurrrsive::got_chars[[11]]$books))
#> spec_object(
#>   books = tib_unspecified("books")
#> )

# Surprising:
tibblify::guess_spec(map(repurrrsive::got_chars, ~ list(books = .x$books)))
#> spec_df(
#>   books = tib_list("books")
#> )
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

When combining specs, the promotion hierarchy would be clearly unspecified -> chr -> chr_vec.

More broadly: would that enable us to think differently about guessing the spec?

**Comment by krlmlr** [comment]
Implementation sketch:

- if `NULL`, return `tib_unspecified()`
- if vector, return atomic spec based on type and length (1 or not 1)
- if named list, iterate over all elements
    - if all results are a vector -- column-major, new `tib_col()`, for now fail
    - if all results are objects -- row-major, `tib_row()`
    - mixed -- would need to construct an example, probably fail?
- if unnamed list, iterate over a sample (*) of elements
    - if all results are a vector -- bind, new `tib_bind()` (#56), for now fail
    - if all results are objects -- combine with `spec_common()`, create `tib_df()`
    - mixed -- would need to construct an example, probably fail?

(*) sample: this also allows speeding up the guessing by limiting the maximum number of items to look at. When later a tibblify error occurs, actionable advice would be to increase that threshold.

Does this make any sense at all?

**Comment by mgirlich** [comment]
This reminds me a little bit of `vec_ptype()` resp. `vec_ptype_common()` with the difference that here we differentiate between scalars and vectors.

**Comment by krlmlr** [comment]
This sounds like a good idea, is it worth starting with a small prototype before changing everything?
