### ISSUE TITLE
Revisit naming scheme

### ISSUE THREAD

**Issue by krlmlr** [mgirlich/tibblify#99]
- `spec_*()` clashes with readr, should we do `tspec_*()` instead?
- Are we happy with the noun + verb form? What about `spec_guess()` vs. `get_spec()` ?
- Should we do a different prefix/suffix for `spec_object()` and `spec_df()` ? Do we even need those, could e.g. `tib_df()` take on the job of `spec_df()` ?
    - Invariant proposal: `guess_spec(x$item)` should be the same as `guess_spec(x)$item` for some definition of `$` in some cases

**Comment by mgirlich** [comment]
> * Should we do a different prefix/suffix for `spec_object()` and `spec_df()` ? Do we even need those, could e.g. `tib_df()` take on the job of `spec_df()` ?

I think we need `spec_df()` and `tib_df()`:

* `tib_df()` has a required argument `key` and has an optional argument `.required`. Both arguments do not make sense for `spec_df()`
* There might also be some arguments that we want to add to `spec_df()` that do not make sense for `tib_df()`

>   * Invariant proposal: `guess_spec(x$item)` should be the same as `guess_spec(x)$item` for some definition of `$` in some cases

Sounds interesting, have to think about this.

**Comment by mgirlich** [comment]
> Are we happy with the noun + verb form? What about `spec_guess()` vs. `get_spec()`?

It is more consistent with readr (e.g. `readr::guess_parser()`) and the tidyverse in general to have verb + noun.

> `spec_*()` clashes with readr, should we do `tspec_*()` instead?

readr uses the following `spec_*()` functions:

* `spec()`: Extract the specification used for reading.
* `spec_delim()`, `spec_csv()`, `spec_csv2()`, `spec_tsv()`, `spec_table()`: Generate a specification

and for the actual specification readr uses

* `cols()` resp. `cols_only()`
* `col_character()`, `col_double()`, ...

For `tibblify()` I don't think it makes sense to speak of columns but rather of fields. Unfortunately, `fields()` is for one thing pretty generic and it is also used already in vctrs. So, for the equivalent to `cols()` I see the following possibilities

* `tspec()`
* `tib_spec()`
* `tibblify_spec()`

* `tfields()`
* `tib_fields()`
* `tibblify_fields()`

The next question is whether we should have

* `tspec_df()`, `tspec_row()`, and `tspec_object()` or
* `tspec_df()`, `tspec_object(output = "list")`, and `tspec_object(output = "tibble")` or
* `tspec(input = "object_list")`, `tspec(input = "object", output = "list")` and `tspec(input = "object", output = "tibble")`

The second and third option feel more in line with the currently added argument `input_form`, `values_to`, and `names_to` for `tib_vector()`.

To specify the fields we could use `tib_*()` or `field_*()`.

For the guessing API I would prefer to explicitly use the prefix `guess_`. This feels way more intuitive than the readr interface.

**Comment by mgirlich** [comment]
@krlmlr Any thoughts on this? Would be nice to have settled on names for the next release.

**Comment by krlmlr** [comment]
I still like `tspec_`, and don't have an informed opinion regarding verb + noun vs. noun + verb.

Should we have a very general `tspec()`, with shortcut functions like `tspec_df()` or whatever feels most natural?

**Comment by mgirlich** [comment]
Closed by #140.
